### ISSUE TITLE
Uncaught TypeError: this._updateCameraUpVector is not a function

### ISSUE THREAD

**Issue by coreuml** [derpylz/babyplots#27]
<!DOCTYPE html>
<html>
<head>
  <script src="babyplots.js"></script>
</head>
<body>
  <canvas id="babyplot"></canvas>
  <script>
    var vis = Baby.Plots("babyplot", {backgroundColor:"#ffffffff"});                      
    vis.fromJSON(myPlotData);
    vis.doRender();
  </script>
</body>
</html>

Uncaught TypeError: this._updateCameraUpVector is not a function
    at Object.e [as Plots] (babyplots.ts:347:14)
    at line3d.html:9:24

I'm using Egde  116.0.1903.0   canary

**Comment by derpylz** [comment]
Hi! Could you provide a bit more information on what you were trying to do? Can you add a minimal version of your "myPlotData"? This will make it easier to find the cause of your issue.
Thank you!

**Comment by coreuml** [comment]
I use the new version.
I created a new HTML page using the sample data（"examples/heatMap.js"）, but the same error still occurred.

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>babyplot</title>
    <script src="dist/babyplots.js"></script>
    <script src="dist/examples/heatMap.js"></script>
</head>
<body>
    <canvas id="babyplot"></canvas>
    <script>		
        var vis = Baby.Plots("babyplot", {backgroundColor:"#ffffffff"});
        vis.fromJSON(heatMapData);
        vis.doRender();
    </script>
</body>
</html>`
the error: 
Uncaught TypeError: this._updateCameraUpVector is not a function
    at Object.e [as Plots] (babyplots.ts:347:14)
    at line3d.html:14:24

**Comment by derpylz** [comment]
Thank you for the additional information.

I believe the issue is because in your code, you initialize the Babyplots object with:

>```javascript
>var vis = Baby.Plots("babyplot", {backgroundColor:"#ffffffff"});
>```

but it should be:

```javascript
var vis = new Baby.Plots("babyplot", {backgroundColor:"#ffffffff"});
```

Notice the `new` keyword before `Baby.Plots`. Can you try adding that and seeing if it solves the problem for you?
